// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © AugustoErni

//@version=5
strategy("Bollinger Bands Modified (Stormer)", overlay=true, process_orders_on_close=true, calc_on_every_tick=false, initial_capital=1200, currency=currency.USD, default_qty_type=strategy.percent_of_equity, default_qty_value=20, pyramiding=0, commission_type=strategy.commission.percent, commission_value=0.12)

length = 20
mult = 0.38
target_factor = 1.6

source = close
basis = ta.sma(source, length)
dev = mult * ta.stdev(source, length)
upper = basis + dev
lower = basis - dev

isLongCondition = ta.crossover(close, upper) ? 1 : 0
isShortCondition = ta.crossunder(close, lower) ? 1 : 0

highestHigh = ta.highest(high, 8)
lowestLow = ta.lowest(low, 8)

isPositionNone = strategy.position_size == 0 ? 1 : 0
isPositionLong = strategy.position_size > 0 ? 1 : 0
isPositionShort = strategy.position_size < 0 ? 1 : 0

var float stopLossLong = 0.0
var float targetLong = 0.0
var float stopLossShort = 0.0
var float targetShort = 0.0
var bool isLongEntry = false
var bool isShortEntry = false

if (isPositionNone)
    isLongEntry := false
    isShortEntry := false
    stopLossLong := 0.0
    targetLong := 0.0
    stopLossShort := 0.0
    targetShort := 0.0
if (isPositionLong and isLongEntry)
    isLongEntry := true
    isShortEntry := false
    stopLossShort := 0.0
    targetShort := 0.0
if (isPositionShort and isShortEntry)
    isShortEntry := true
    isLongEntry := false
    stopLossLong := 0.0
    targetLong := 0.0

if (isLongCondition and not isLongEntry)
    isLongEntry := true
    stopLossLong := lowestLow
    targetLong := close + math.abs(close - stopLossLong) * target_factor
    strategy.entry("Long", strategy.long)
    strategy.exit("Exit Long", "Long", stop=stopLossLong, limit=targetLong)

if (isShortCondition and not isShortEntry)
    isShortEntry := true
    stopLossShort := highestHigh
    targetShort := close - math.abs(close - stopLossShort) * target_factor
    strategy.entry("Short", strategy.short)
    strategy.exit("Exit Short", "Short", stop=stopLossShort, limit=targetShort)

plot(upper, color=color.blue)
plot(basis, color=color.gray)
plot(lower, color=color.blue)
plot(stopLossLong, 'stopLossLong')
plot(targetLong, 'targetLong')
plot(stopLossShort, 'stopLossShort')
plot(targetShort, 'targetShort')
plot(isLongEntry ? 1 : 0, 'isLongEntry')
plot(isShortEntry ? 1 : 0, 'isShortEntry')
plot(strategy.position_size, 'strategy.position_size')
