// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © AugustoErni

//@version=5
strategy("Simple Alert Strategy", overlay=true, process_orders_on_close=true)

// Calculate the moving average
ma = ta.sma(close, 3)

// Check if the current close price is above the moving average
above_ma = close > ma

// Check if the previous close price was below the moving average
below_ma = close[1] < ma[1]

// Alert if the current close is above the moving average and the previous close was below the moving average
if above_ma and below_ma
    alert_message = '{ "strategyName": "Simple Alert Strategy", "pair": "ETH/USDT", "chartTimeframe": { "chronoAmount": "1", "chronoUnit": "MINUTE" }, "side": "buy", "entry": ' + str.tostring(close) + ', "signalTradeType": "INDICATOR" }'
    strategy.entry("Buy", strategy.long, alert_message=alert_message )
    alert(alert_message)

// Alert if the current close is below the moving average and the previous close was above the moving average
if not above_ma and not below_ma
    alert_message = '{ "strategyName": "Simple Alert Strategy", "pair": "ETH/USDT", "chartTimeframe": { "chronoAmount": "1", "chronoUnit": "MINUTE" }, "side": "sell", "entry": ' + str.tostring(close) + ', "signalTradeType": "INDICATOR" }'
    strategy.entry("Sell", strategy.short, alert_message=alert_message)
    alert(alert_message)