// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © AugustoErni

//@version=5

library("rsi_lib", overlay=true)

rsiFunction(rsiLengthPeriod) =>
    lengthPeriod = rsiLengthPeriod
    source = close
    differenceSource = ta.change(source)
    gain = na(differenceSource) ? na : math.max(differenceSource, 0)
    loss = na(differenceSource) ? na : -math.min(differenceSource, 0)
    averageGain = ta.rma(gain, lengthPeriod)
    averageLoss = ta.rma(loss, lengthPeriod)
    relativeStrength = (averageGain / averageLoss)
    relativeStrengthIndex = (100 - (100 / (1 + relativeStrength)))
	relativeStrengthIndex