// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © AugustoErni

//@version=5
indicator(title="Exponential Moving Average (Trend Following)", shorttitle="EMA (Trend Following)", overlay=true)

lengthPeriod = input.int(defval=21, title="Length Period", step=1, tooltip="Calculate the exponential moving average (EMA) over the specified period.")

source = close

alpha = 2 / (lengthPeriod + 1)

sma = 0.0
for i = 0 to lengthPeriod - 1
    sma := sma + source[i] / lengthPeriod

ema = 0.0
ema := na(ema[1]) ? sma : ((alpha * source) + ((1 - alpha) * nz(ema[1])))

plot(ema, title="EMA", color=color.blue)