// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © AugustoErni

//@version=5
indicator("Evening Star Pattern (Candlestick Pattern)", overlay=true)

showEveningStar = input.bool(defval=true, title="Show Evening Star", tooltip="Show or hide the Evening Star pattern.")
dojiThreshold = input.float(0.1, title="Doji Threshold (0.1 = 10%)", step=0.01)
weakCandleThreshold = input.float(0.3, title="Weak Candle Threshold (0.3 = 30%)", step=0.01)

isDoji = math.abs(close - open) <= (high - low) * dojiThreshold
isWeakCandle = math.abs(close - open) <= (high - low) * weakCandleThreshold

isBullishCandle = close > open
isBearishCandle = open > close

isConditionFirstCandle = isBullishCandle[2] and open[2] < low[1] and not isDoji and not isWeakCandle
isConditionSecondCandle = isDoji[1] or isWeakCandle[1]
isConditionThirdCandle = close < low[1] and not isDoji and not isWeakCandle

isEveningStar = isConditionFirstCandle and isConditionSecondCandle and isConditionThirdCandle

barcolor(isEveningStar ? color.black : na)
barcolor(isEveningStar and isBullishCandle[1] ? color.white : isEveningStar and isBearishCandle[1] ? color.black : na, offset=-1)
barcolor(isEveningStar and isBullishCandle[2] ? color.white : na, offset=-2)

plotshape(isEveningStar and showEveningStar, title="Evening Star", style=shape.arrowdown, location=location.abovebar, color=color.rgb(0, 0, 0), text="Evening Star", textcolor=color.red)
