// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © AugustoErni

//@version=5
indicator("Hammer and Hanging Man (Candlestick Pattern)", overlay=true)

hammerHangingManBodySizeThreshold = input.float(defval=0.34, title="Hammer/Hanging Man body size threshold in percentage (0.34 = 34%)", step=0.01)
hammerHangingManLowerShadowMultiplier = input.float(defval=1.8, title="Hammer/Hanging Man lower shadow multiplier", step=0.1)
hammerHangingManUpperShadowThreshold = input.float(defval=0.05, title="Hammer/Hanging Man upper shadow threshold in percentage (0.05 = 5%)", step=0.01)

showHammer = input.bool(defval=true, title="Show Hammer", tooltip="Show or hide the Hammer pattern.")
showHangingMan = input.bool(defval=true, title="Show Hanging Man", tooltip="Show or hide the Hanging Man pattern.")

isBullishCandle = close > open
isBearishCandle = open > close
realBody = math.abs(close - open)
upperShadow = high - math.max(close, open)
lowerShadow = math.min(close, open) - low

isSmallRealBody = realBody <= hammerHangingManBodySizeThreshold * (high - low)
isLongLowerShadow = lowerShadow >= hammerHangingManLowerShadowMultiplier * realBody
isShortUpperShadow = upperShadow <= hammerHangingManUpperShadowThreshold * (high - low)

isHammer = isBullishCandle and isSmallRealBody and isLongLowerShadow and isShortUpperShadow
isHangingMan = isBearishCandle and isSmallRealBody and isLongLowerShadow and isShortUpperShadow

barcolor(isHammer ? color.white : isHangingMan ? color.black : na)

plotshape(isHammer and showHammer, title="Hammer", style=shape.arrowup, location=location.belowbar, color=color.rgb(255, 255, 255), text="Hammer", textcolor=color.green)
plotshape(isHangingMan and showHangingMan, title="Hanging Man", style=shape.arrowdown, location=location.abovebar, color=color.rgb(0, 0, 0), text="Hanging Man", textcolor=color.red)