// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © AugustoErni

//@version=5
indicator("Morning Star Pattern (Candlestick Pattern)", overlay=true)

showMorningStar = input.bool(defval=true, title="Show Morning Star", tooltip="Show or hide the Morning Star pattern.")
dojiThreshold = input.float(0.1, title="Doji Threshold (0.1 = 10%)", step=0.01)
weakCandleThreshold = input.float(0.3, title="Weak Candle Threshold (0.3 = 30%)", step=0.01)

isDoji = math.abs(close - open) <= (high - low) * dojiThreshold
isWeakCandle = math.abs(close - open) <= (high - low) * weakCandleThreshold

isBullishCandle = close > open
isBearishCandle = open > close

isConditionFirstCandle = isBearishCandle[2] and open[2] > high[1]
isConditionSecondCandle = isDoji[1] or isWeakCandle[1]
isConditionThirdCandle = close > high[1]

isMorningStar = isConditionFirstCandle and isConditionSecondCandle and isConditionThirdCandle

barcolor(isMorningStar ? color.white : na)
barcolor(isMorningStar and isBullishCandle[1] ? color.white : isMorningStar and isBearishCandle[1] ? color.black : na, offset=-1)
barcolor(isMorningStar and isBearishCandle[2] ? color.black : na, offset=-2)

plotshape(isMorningStar and showMorningStar, title="Morning Star", style=shape.arrowup, location=location.belowbar, color=color.rgb(255, 255, 255), text="Morning Star", textcolor=color.green)