// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © AugustoErni

//@version=5
indicator("Stochastic (Momentum Oscillator)", shorttitle="Stochastic", overlay = false)

length = input.int(14, minval=1, title="Length")
smoothK = input.int(3, minval=1, title="K")
smoothD = input.int(3, minval=1, title="D")

lowestLow = ta.lowest(low, length)
highestHigh = ta.highest(high, length)

K = ta.sma(100 * (close - lowestLow) / (highestHigh - lowestLow), smoothK)

D = ta.sma(K, smoothD)

plot(K, color=color.blue, title="%K")
plot(D, color=color.orange, title="%D")
hline(80, "Upper Level", color=color.gray)
hline(20, "Lower Level", color=color.gray)
